In [ ]:
import numpy as np
rainfall_data= [120, 85, 90, 110, 95, 100, 105, 85, 115, 130, 125, 140]
rainfall_array=np.array(rainfall_data)
print(rainfall_array)

[120  85  90 110  95 100 105  85 115 130 125 140]


In [ ]:
first_quater=rainfall_array[:3]
print(first_quater)



[120  85  90]


In [ ]:
jully_rainfall=rainfall_array[6]
print(jully_rainfall)



105


In [ ]:
quarters = np.split(rainfall_array, 4)

for i, quarter in enumerate(quarters, start=0):
    print(f"Quarter {i}: {quarter}")


Quarter 0: [120  85  90]
Quarter 1: [110  95 100]
Quarter 2: [105  85 115]
Quarter 3: [130 125 140]


In [ ]:
quarters = np.split(rainfall_array, 4)

for i, quarter in enumerate(quarters, start=0):
    total_rainfall = np.sum(quarter)
    max_rainfall = np.max(quarter)
    max_rainfall_month = np.argmax(quarter) + 1
    print(f"Quarter {i}: Total Rainfall = {total_rainfall}, Highest Rainfall = {max_rainfall} (Month {max_rainfall_month})")


Quarter 0: Total Rainfall = 295, Highest Rainfall = 120 (Month 1)
Quarter 1: Total Rainfall = 305, Highest Rainfall = 110 (Month 1)
Quarter 2: Total Rainfall = 305, Highest Rainfall = 115 (Month 3)
Quarter 3: Total Rainfall = 395, Highest Rainfall = 140 (Month 3)


1.a:Basic NumPy Array Operations


In [ ]:
#Create a NumPy array from the given dataset.
data=[
    [85,92,78,90],
    [88,79,85,93],
    [91,85,87,88],
    [76,88,84,91]
]
scores_array=np.array(data)
print(scores_array)

[[85 92 78 90]
 [88 79 85 93]
 [91 85 87 88]
 [76 88 84 91]]


In [ ]:
#Retrieve the attributes of the array (shape, size, dtype).
shape=scores_array.shape
size=scores_array.size
dtype=scores_array.dtype
print(f"shape:{shape},\nsize:{size},\ndytype:{dtype}")


shape:(4, 4),
size:16,
dytype:int64


In [ ]:
#Slice the array to get the scores of the first two students.
first_two_students=scores_array[:2, :]
print(first_two_students)

[[85 92 78 90]
 [88 79 85 93]]


In [ ]:
#Index the array to get the score of the second student in Chemistry.
chemistry_scores=scores_array[1,1]
print(chemistry_scores)

79


1.b: Basic NumPy Array Operations

In [ ]:
#Create a NumPy array from the sales revenue list.
import numpy as np
months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
sales_revenue = [12000, 15000, 17000, 13000, 16000, 18000, 20000, 19000, 17500, 16000, 15000, 16500]
sales_revenue_array = np.array(sales_revenue)
print(sales_revenue_array)



[12000 15000 17000 13000 16000 18000 20000 19000 17500 16000 15000 16500]


In [ ]:
#Retrieve the attributes of the array (shape, size, dtype).
shape=sales_revenue_array.shape
size=sales_revenue_array.size
dtype=sales_revenue_array.dtype
print(f"shape:{shape},size:{size},dtype:{dtype}")


shape:(12,),size:12,dtype:int64


In [ ]:
#Slice the array to get the sales revenue for the first half of the year.
first_half_revenue=sales_revenue_array[:6]
print(first_half_revenue)


[12000 15000 17000 13000 16000 18000]


In [ ]:
#Index the array to get the sales revenue for May.
may_revenue=sales_revenue_array[4]
print(may_revenue)


16000


In [ ]:
#Calculate the total sales revenue for the year
total_revenue=np.sum(sales_revenue_array)
print(total_revenue)

195000


In [ ]:
#Find the month with the highest sales revenue. Expected Output: Shape: (12,) Size: 12 Data type: int32 First half of the year sales revenue: [12000 15000 17000 13000 16000 18000] Sales revenue for May: 16000 Total sales revenue for the year: 195500 Month with highest sales revenue: July
max_sales_index = sales_revenue_array.argmax()
month_with_highest_sales = months[max_sales_index]
print("Month with highest sales revenue:", month_with_highest_sales)

Month with highest sales revenue: July


1.c: Universal Functions

In [ ]:
#Create NumPy Arrays for Each Performance Metric
import numpy as np
performance_data = {
    'running_speed': [10.5, 9.8, 11.2, 10.0, 9.7],
    'jump_height': [2.1, 2.3, 2.0, 2.4, 2.2],
    'throw_distance': [60.5, 62.0, 59.8, 61.2, 63.5]
}
running_speed = np.array(performance_data['running_speed'])
jump_height = np.array(performance_data['jump_height'])
throw_distance = np.array(performance_data['throw_distance'])
print("Running Speed Array:", running_speed)
print("Jump Height Array:", jump_height)
print("Throw Distance Array:", throw_distance)



Running Speed Array: [10.5  9.8 11.2 10.   9.7]
Jump Height Array: [2.1 2.3 2.  2.4 2.2]
Throw Distance Array: [60.5 62.  59.8 61.2 63.5]


In [ ]:
#Calculate the square of the running speeds using a universal function.
running_speed = np.array(performance_data['running_speed'])
squared_running_speed = np.square(running_speed)
print("Squared Running Speeds:", squared_running_speed)


Squared Running Speeds: [110.25  96.04 125.44 100.    94.09]


In [ ]:
#Normalize the Jump Heights.
mean_jump_height = np.mean(jump_height)
std_jump_height = np.std(jump_height)

normalized_jump_height = (jump_height - mean_jump_height) / std_jump_height
print("Normalized Jump Heights:", normalized_jump_height)


Normalized Jump Heights: [-0.70710678  0.70710678 -1.41421356  1.41421356  0.        ]


In [ ]:
#Apply the Exponential Function to the Throw Distances.
exponential_throw_distance = np.exp(throw_distance)
print("Exponential Throw Distances:", exponential_throw_distance)


Exponential Throw Distances: [1.88285187e+26 8.43835667e+26 9.34996570e+25 3.79159806e+26
 3.78180909e+27]


In [ ]:
#Calculate the Logarithm of the Normalized Jump Heights.
if np.all(normalized_jump_height > 0):
    log_normalized_jump_height = np.log(normalized_jump_height)
    print("Logarithm of Normalized Jump Heights:", log_normalized_jump_height)
else:
    print("Normalized Jump Heights contain non-positive values, cannot compute logarithm.")


Normalized Jump Heights contain non-positive values, cannot compute logarithm.


In [ ]:
#Apply the Sine Function to the Running Speeds.
sine_running_speed = np.sin(running_speed)
print("Sine of Running Speeds:", sine_running_speed)


Sine of Running Speeds: [-0.87969576 -0.36647913 -0.97917773 -0.54402111 -0.27176063]


1.d: Aggregate Functions

In [ ]:
#Import NumPy and Create Arrays.
import numpy as np
returns_data = {
    'portfolio_A': [0.05, 0.02, 0.04, 0.03, 0.06, 0.01],
    'portfolio_B': [0.04, 0.03, 0.05, 0.02, 0.01, 0.04],
    'portfolio_C': [0.03, 0.01, 0.02, 0.03, 0.04, 0.05]
}

returns_A = np.array(returns_data['portfolio_A'])
returns_B = np.array(returns_data['portfolio_B'])
returns_C = np.array(returns_data['portfolio_C'])
print("Returns for portfolio A:", returns_A)
print("Returns for portfolio B:", returns_B)
print("Returns for portfolio C:", returns_C)


Returns for portfolio A: [0.05 0.02 0.04 0.03 0.06 0.01]
Returns for portfolio B: [0.04 0.03 0.05 0.02 0.01 0.04]
Returns for portfolio C: [0.03 0.01 0.02 0.03 0.04 0.05]


In [ ]:
# Calculate Total Return for Each Portfolio.
total_return_A = np.sum(returns_A)
total_return_B = np.sum(returns_B)
total_return_C = np.sum(returns_C)

print(f"Total return for portfolio A: {total_return_A:.4f}")
print(f"Total return for portfolio B: {total_return_B:.4f}")
print(f"Total return for portfolio C: {total_return_C:.4f}")


Total return for portfolio A: 0.2100
Total return for portfolio B: 0.1900
Total return for portfolio C: 0.1800


In [ ]:
#Calculate Mean Monthly Return for Each Portfolio.
mean_return_A = np.mean(returns_A)
mean_return_B = np.mean(returns_B)
mean_return_C = np.mean(returns_C)

print(f"Mean monthly return for portfolio A: {mean_return_A:.4f}")
print(f"Mean monthly return for portfolio B: {mean_return_B:.4f}")
print(f"Mean monthly return for portfolio C: {mean_return_C:.4f}")


Mean monthly return for portfolio A: 0.0350
Mean monthly return for portfolio B: 0.0317
Mean monthly return for portfolio C: 0.0300


In [ ]:
# Find the Portfolio with the Highest Mean Return.
mean_returns = {
    'portfolio_A': mean_return_A,
    'portfolio_B': mean_return_B,
    'portfolio_C': mean_return_C
}

best_portfolio = max(mean_returns, key=mean_returns.get)
print(f"The portfolio with the highest mean return is {best_portfolio}")


The portfolio with the highest mean return is portfolio_A


In [ ]:
# Calculate the Overall Average Return Across All Portfolios.
all_returns = np.concatenate([returns_A, returns_B, returns_C])
overall_average_return = np.mean(all_returns)
print(f"Overall average return across all portfolios: {overall_average_return:.4f}")


Overall average return across all portfolios: 0.0322


In [ ]:
# Determine the Variance and Standard Deviation for Each Portfolio.
variance_A = np.var(returns_A)
std_dev_A = np.std(returns_A)

variance_B = np.var(returns_B)
std_dev_B = np.std(returns_B)

variance_C = np.var(returns_C)
std_dev_C = np.std(returns_C)

print(f"Variance and standard deviation for portfolio A: {variance_A:.4f}, {std_dev_A:.4f}")
print(f"Variance and standard deviation for portfolio B: {variance_B:.4f}, {std_dev_B:.4f}")
print(f"Variance and standard deviation for portfolio C: {variance_C:.4f}, {std_dev_C:.4f}")


Variance and standard deviation for portfolio A: 0.0003, 0.0171
Variance and standard deviation for portfolio B: 0.0002, 0.0134
Variance and standard deviation for portfolio C: 0.0002, 0.0129


Exercise 2.a: Analyzing Restaurant Performance

In [ ]:
import numpy as np
import pandas as pd

data = [(601, 12000, 8000, np.nan),
        (602, 15000, 13000, 14000),
        (603, 16000, np.nan, 12000),
        (602, 15000, 13000, 14000),
        (604, 11000, np.nan, 9000),
        (601, 12000, 8000, np.nan)]

data_array = np.array(data)
df = pd.DataFrame(data_array, columns=['Branch ID', 'Food Sales', 'Beverage Sales', 'Dessert Sales'])
missing_values = df.isnull().sum()
duplicates = df.duplicated(subset='Branch ID', keep='first').sum()
medians = df.median()
df.fillna(medians, inplace=True)
df.drop_duplicates(subset='Branch ID', keep='first', inplace=True)
def min_max_normalize(column):
    return (column - column.min()) / (column.max() - column.min())
normalized_df = df.copy()
normalized_df[['Food Sales', 'Beverage Sales', 'Dessert Sales']] = df[['Food Sales', 'Beverage Sales', 'Dessert Sales']].apply(min_max_normalize)
normalized_stats = normalized_df[['Food Sales', 'Beverage Sales', 'Dessert Sales']].agg(['mean', 'median', 'std'])
highest_variability_category = normalized_stats.loc['std'].idxmax()
{
    "missing_values": missing_values,
    "duplicates": duplicates,
    "normalized_stats": normalized_stats,
    "highest_variability_category": highest_variability_category
}


{'missing_values': Branch ID         0
 Food Sales        0
 Beverage Sales    2
 Dessert Sales     2
 dtype: int64,
 'duplicates': 2,
 'normalized_stats':         Food Sales  Beverage Sales  Dessert Sales
 mean      0.500000        0.500000       0.600000
 median    0.500000        0.500000       0.700000
 std       0.476095        0.408248       0.432049,
 'highest_variability_category': 'Food Sales'}

2b Analysis of Credit Card Expenditure

In [ ]:
import numpy as np

data = np.array([
    [401, 2000, 15],
    [402, 2500, 18],
    [403, np.nan, 20],
    [404, 2700, 22],
    [405, 2000, 15],
    [406, 2000, np.nan],
    [407, 3200, 25],
    [408, 2500, 18],
    [409, 2800, np.nan],
    [401, 2000, 15]
])


median_spending = np.nanmedian(data[:, 1])
median_transactions = np.nanmedian(data[:, 2])


data[np.isnan(data[:, 1]), 1] = median_spending
data[np.isnan(data[:, 2]), 2] = median_transactions


_, unique_indices = np.unique(data[:, 0], return_index=True)
data = data[sorted(unique_indices)]

min_spending, max_spending = np.min(data[:, 1]), np.max(data[:, 1])
min_transactions, max_transactions = np.min(data[:, 2]), np.max(data[:, 2])

data[:, 1] = (data[:, 1] - min_spending) / (max_spending - min_spending)
data[:, 2] = (data[:, 2] - min_transactions) / (max_transactions - min_transactions)

mean_spending = np.mean(data[:, 1])
median_spending = np.median(data[:, 1])
std_spending = np.std(data[:, 1])
mean_transactions = np.mean(data[:, 2])
median_transactions = np.median(data[:, 2])
std_transactions = np.std(data[:, 2])

correlation = np.corrcoef(data[:, 1], data[:, 2])[0, 1]

print("Processed Data:")
print(data)
print("\nDescriptive Statistics:")
print(f"Monthly Spending - Mean: {mean_spending}, Median: {median_spending}, Std Dev: {std_spending}")
print(f"Number of Transactions - Mean: {mean_transactions}, Median: {median_transactions}, Std Dev: {std_transactions}")
print(f"\nCorrelation between Monthly Spending and Number of Transactions: {correlation}")


Processed Data:
[[4.01000000e+02 0.00000000e+00 0.00000000e+00]
 [4.02000000e+02 4.16666667e-01 3.00000000e-01]
 [4.03000000e+02 4.16666667e-01 5.00000000e-01]
 [4.04000000e+02 5.83333333e-01 7.00000000e-01]
 [4.05000000e+02 0.00000000e+00 0.00000000e+00]
 [4.06000000e+02 0.00000000e+00 3.00000000e-01]
 [4.07000000e+02 1.00000000e+00 1.00000000e+00]
 [4.08000000e+02 4.16666667e-01 3.00000000e-01]
 [4.09000000e+02 6.66666667e-01 3.00000000e-01]]

Descriptive Statistics:
Monthly Spending - Mean: 0.3888888888888889, Median: 0.4166666666666667, Std Dev: 0.32394177193585005
Number of Transactions - Mean: 0.37777777777777777, Median: 0.3, Std Dev: 0.3010270485365348

Correlation between Monthly Spending and Number of Transactions: 0.848237190379443
